# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [ published ]

env:
  DIST_DIR: ./dist
  BUILD_ARTIFACT: dist.tar.gz
  NPM_TOKEN: ${{secrets.NPM_TOKEN}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn test
      - name: Tar build dist
        run: tar -czvf ${BUILD_ARTIFACT} ${DIST_DIR}
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: ./${{ env.BUILD_ARTIFACT }}
          if-no-files-found: error  # 找不到文件时报错

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifact
      - name: unTar storybook docs
        run: tar -xzvf ./${BUILD_ARTIFACT}
      - run: npm publish
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
